AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'Rakefile'
Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
  Exclude:
    - 'config/**/*'
Rails/TimeZone:
  Enabled: false
SignalException:
  Enabled: false
Style/PredicateName:
  NamePrefix:
    - is_
    - have_
  NamePrefixBlacklist:
    - is_
    - have_
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true
Style/IfUnlessModifier:
  MaxLineLength: 100
