defaults: &defaults
  google_client_id:   go_to_google_dev_console_add_new_app
  google_secret:      and_paste_config_here
  google_domain:      fill_in_your_domain
  github_client_id:   go_to_github_settings_and_add_new_app
  github_secret:      and_paste_config_here
  api_token:          miamiamia
  secret_token_key:   miaaaaamia
  company_name:       Company
  emails:
    from:             default_address_used_to_send_emails
    pm:               pms_email_address
    internal:         example.com
    social:           example.com
  tld_length:         1
  feature:
    new_available_view: false

heroku_settings: &heroku_settings
  <<: *defaults
  github_client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
  github_secret:    <%= ENV['GITHUB_CLIENT_SECRET'] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_secret:    <%= ENV['GOOGLE_CLIENT_SECRET'] %>
  google_domain:    <%= ENV['GOOGLE_DOMAIN'] %>
  api_token:        <%= ENV['API_TOKEN'] %>
  secret_token_key: <%= ENV['SECRET_TOKEN_KEY'] %>
  sendgrid:
    login:          <%= ENV['SENDGRID_USERNAME'] %>
    password:       <%= ENV['SENDGRID_PASSWORD'] %>
    domain:         <%= ENV['SENDGRID_DOMAIN'] %>
  emails:
    from:             <%= ENV['EMAIL_FROM'] %>
    pm:               <%= ENV['EMAIL_PM'] %>
    internal:         <%= ENV['EMAIL_INTERNAL'] %>
    social:           <%= ENV['EMAIL_SOCIAL'] %>
  company_name:       <%= ENV['COMPANY_NAME'] %>
  domain:             <%= ENV['DOMAIN'] %>
  tld_length:         <%= ENV['TLD_LENGTH'] %>
  feature:
    new_available_view: <%= ENV['AVAILABLE_VIEW'] %>

development:
  <<: *defaults
  domain: people.dev
  feature:
    new_available_view: true

test:
  <<: *defaults
  domain: people.test

staging:
  <<: *heroku_settings

production:
  <<: *heroku_settings
